#Traefik implementado utilizando o halm
rbac:
  enabled: true

serviceAccount:
  name: traefik-ingress-controller

deployment:
  enabled: false

daemonSet:
  enabled: true
  annotations: {}
  labels:
    k8s-app: traefik-ingress-lb
  podAnnotations: {}
  podLabels:
    k8s-app: traefik-ingress-lb
    name: traefik-ingress-lb
  terminationGracePeriodSeconds: 60
  hostPort:
    httpEnabled: true
    httpPort: 80
    httpsEnabled: false
  securityContext:
    capabilities:
      drop:
        - ALL
      add:
        - NET_BIND_SERVICE

ports:
  web:
    port: 80
    hostPort: 80
  admin:
    port: 8080
    hostPort: 8080
  https:
    enabled: false

providers:
  kubernetesIngress:
    enabled: true
    ingressClass: traefik

logs:
  general:
    level: INFO

service:
  enabled: true
  type: LoadBalancer
  annotations: {}
  labels: {}
  spec:
    selector:
      k8s-app: traefik-ingress-lb
    ports:
      - name: web
        protocol: TCP
        port: 80
        targetPort: 80
      - name: admin
        protocol: TCP
        port: 8080
        targetPort: 8080

additionalArguments:
  - --api.dashboard=true
  - --api.insecure=true